import { Metadata } from "next";

// components
import Hero from "@/app/Home3/components/Hero";
import ExploreProperties from "@/app/Home3/components/ExploreProperties";
import PropertyStats from "@/app/Home3/components/PropertyStats";
import DiscoverDeals from "@/app/Home3/components/DiscoverDeals";
import ExploreCities from "@/app/Home3/components/ExploreCities";
import RecentPropertiesRent from "@/app/Home3/components/RecentPropertiesRent";
import RecentPropertiesSale from "@/app/Home3/components/RecentPropertiesSale";
import HowItWorks from "@/app/Home3/components/HowItWorks";
import DiscoverPlace from "@/app/Home3/components/DiscoverPlace";
import WhyChooseUs from "@/app/Home3/components/WhyChooseUs";
import TrustBy from "@/components/homepage/TrustedBy";

// metadata
export const metadata: Metadata = {
  title: "Home - 3",
  description: "Generated by create next app - (discription)",
  keywords: "ui/ux study, spadasoft, nextjs, react, home2",
};

const page = () => {
  return (
    <>
      <Hero />
      <ExploreProperties />
      <PropertyStats />
      <DiscoverDeals />
      <ExploreCities />
      <RecentPropertiesRent />
      <RecentPropertiesSale />
      <HowItWorks />
      <DiscoverPlace />
      <WhyChooseUs />
      <TrustBy className="pt-[15px] pb-[155px]" />
    </>
  );
};

export default page;
