import { Metadata } from "next";

// components
import Hero from "@/app/Home2/components/Hero";
import WhyChooseUs from "@/app/Home2/components/WhyChooseUs";
import FeaturedProperties from "@/app/Home2/components/FeaturedProperties";
import DiscoverCities from "@/app/Home2/components/DiscoverCities";
import Services from "@/app/Home2/components/Services";
import Testimonials from "@/components/homepage/Testimonials";
import BestProperties from "@/app/Home2/components/BestProperties";
import MeetTeem from "@/app/Home2/components/MeetTeem";
import PopularMarkets from "@/app/Home2/components/PopularMarkets";

// metadata
export const metadata: Metadata = {
  title: "Home - 2",
  description: "Generated by create next app - (discription)",
  keywords: "ui/ux study, spadasoft, nextjs, react, home2",
};

const page = () => {
  return (
    <>
      <Hero />
      <WhyChooseUs />
      <FeaturedProperties />
      <DiscoverCities />
      <Services />
      <Testimonials className="bg-white-warm testimonialSwiperBtnH2" />
      <BestProperties />
      <MeetTeem />
      <PopularMarkets />
    </>
  );
};

export default page;
