import { Metadata } from "next";
import {
  TrustedByContent,
  TrustedByContentH4,
} from "@/app/Home4/assets/content";
// components
import Hero from "@/app/Home4/components/Hero";
import TrustedBy1 from "@/components/homepage/TrustedBy";
import TrustedBy2 from "@/components/homepage/TrustedBy";
import FindDreamHouse from "@/app/Home4/components/FindDreamHouse";
import FeaturedCategories from "@/app/Home4/components/FeaturedCategories";
import RecentPropertiesRent from "@/app/Home4/components/RecentPropertiesRent";
import WhyChooseUs from "@/app/Home4/components/WhyChooseUs";
import Testimonials from "@/app/Home4/components/Testimonials";
import PropertiesByArea from "@/app/Home4/components/PropertiesByArea";
import RecentArticles from "@/components/homepage/RecentArticles";
import BuySellCta from "@/app/Home4/components/BuySellCta";

// metadata
export const metadata: Metadata = {
  title: "Home - 4",
  description: "Generated by create next app - (discription)",
  keywords: "ui/ux study, spadasoft, nextjs, react, home4",
};

const page = () => {
  return (
    <>
      <Hero />
      <TrustedBy1
        className="bg-black-deep text-white py-[75px]"
        data={TrustedByContent}
      />
      <FindDreamHouse />
      <FeaturedCategories />
      <RecentPropertiesRent />
      <WhyChooseUs />
      <Testimonials />
      <TrustedBy2 data={TrustedByContentH4} className="pt-[164px] pb-[160px]" />
      <PropertiesByArea />
      <RecentArticles className="pt-[180px] pb-[30px] bg-white" />
      <BuySellCta />
    </>
  );
};

export default page;
