import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// components
import "@/assets/globals.css";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";

export const metadata: Metadata = {
  title: "UI/UX study - spadasoft",
  description: "Generated by create next app - (discription)",
  keywords: "UI/UX study, spadasoft, nextjs, react",
  creator: "haseeb.arshad@spadasoftinc.com",
  publisher: "spadasoftinc.com",
  icons: {
    icon: "/src/assets/favicon.ico",
    // shortcut: "/assets/favicon.ico",
    // apple: "/assets/favicon.ico",
  },
};

const RobotoFont = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
  display: "swap",
  style: ["normal", "italic"],
  fallback: ["sans-serif"],
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoFont.variable} antialiased p-5`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
